#!/usr/bin/env python

from gi.repository import PackageKitGlib as pk
from gi.repository import Gtk,GLib
import signal

def check_for_updates():
	client = pk.Client()
	updates = client.get_updates(0,None,bla,None )
	package_sack = updates.get_package_sack()
	package_array = package_sack.get_array()
	print "There are "+ str(len(package_array)) + " package updates"
	return True

def bla(a, b, c):
	pass


def main():
	signal.signal(signal.SIGINT, signal.SIG_DFL)

	statusicon = Gtk.StatusIcon()
	statusicon.set_from_stock(Gtk.STOCK_HOME)
	statusicon.connect("popup-menu", lambda a,b,c: Gtk.main_quit())

	GLib.timeout_add_seconds(30,check_for_updates)
	Gtk.main()
main()

